### ISSUE TITLE
External schema API

### ISSUE THREAD

**Issue by spacekookie** [rust-db/barrel#55]
This is a tracking issue for a schema API that makes it easier for external tools (such as `diesel`) to hook into the migration process.

Notes from the wiki (need to be restructured)

- The idea behind this is that ORMs can provide additional schema information to a migration, 
	i.e. the columns that already exist, etc.
- This allows features such as Sqlite-renames to be generated, 
	without needing to push that responsibility to the user.
- This API shouldn't be `diesel` specific: we want other frameworks to be able 
	to provide the same information to `barrel`!

**TODOs**

- [ ] Design API & talk to Sean (diesel)
- [ ] Do some diesel PRs implementing this
- [ ] Implement it on our end
